# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etluser',
            old_name='sourcefile',
            new_name='source_file',
        ),
        migrations.RenameField(
            model_name='etluser',
            old_name='username',
            new_name='user_name',
        ),
    ]
