# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_auto_20180711_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='containerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dataContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=30)),
                ('container_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etl.containerType')),
            ],
        ),
        migrations.AddField(
            model_name='etluser',
            name='source_sql',
            field=models.TextField(default='SELECT * FROM'),
        ),
        migrations.AddField(
            model_name='etluser',
            name='target_sql',
            field=models.TextField(default='SELECT * FROM'),
        ),
        migrations.AddField(
            model_name='etluser',
            name='truncate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etluser',
            name='source_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_container', to='etl.dataContainer'),
        ),
        migrations.AddField(
            model_name='etluser',
            name='target_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_container', to='etl.dataContainer'),
        ),
    ]
