# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_auto_20180711_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='sourceContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(default='未分类', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='targetContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(default='未分类', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='datacontainer',
            name='container_type',
        ),
        migrations.AlterField(
            model_name='etluser',
            name='source_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_container', to='etl.sourceContainer'),
        ),
        migrations.AlterField(
            model_name='etluser',
            name='source_sql',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='etluser',
            name='target_container',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_container', to='etl.targetContainer'),
        ),
        migrations.AlterField(
            model_name='etluser',
            name='target_sql',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='containerType',
        ),
        migrations.DeleteModel(
            name='dataContainer',
        ),
    ]
